name: Feature request
description: Describe something that would make playing easier
body:
  - type: textarea
    id: problem
    attributes:
      label: What would you like to do?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Your idea
