import {t,getLocale,ServiceMessage} from './i18n';
import React,{useEffect,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {Box,Search,RefreshCw,Trash2,LoaderCircle} from 'lucide-react';
import {Select} from './Select';
import './installed-mods.css';
type Json=Record<string,any>;
const categories:Record<string,string>={optimization:'性能优化',adventure:'冒险探索',worldgen:'世界生成',decoration:'建筑装饰',technology:'科技自动化',magic:'魔法',storage:'仓储整理',equipment:'装备工具',mobs:'生物',food:'食物农业',transportation:'交通运输','game-mechanics':'游戏机制',social:'社交联机',utility:'实用工具',management:'服务器管理',library:'前置依赖',cursed:'趣味整活',uncategorized:'未分类'};
const label=(c:string)=>t(categories[c]||c);
export function InstalledMods({item,busy,onRemove,onVersion}:{item:Json;busy:boolean;onRemove:(m:Json)=>void;onVersion:(p:Json)=>void}){
 const [catalog,setCatalog]=useState<Json>({}),[loading,setLoading]=useState(false),[warning,setWarning]=useState(''),[retry,setRetry]=useState(0),[category,setCategory]=useState(''),[query,setQuery]=useState(''),[side,setSide]=useState('');
 const key=item.mods.map((m:Json)=>m.sha512).sort().join(',');
 useEffect(()=>{let active=true;setLoading(true);setWarning('');invoke<Json>('call',{action:'installed-mod-categories',payload:{id:item.instance.instanceId,refresh:retry>0}}).then(r=>{if(active){setCatalog(r.entries);setWarning(r.warning||'')}}).catch(()=>{if(active)setWarning(t("暂时无法识别分类，可以稍后重试。"))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[item.instance.instanceId,key,retry]);
 const rows:Json[]=item.mods.map((m:Json)=>{const meta=catalog[m.sha512]||{};const tags=meta.categories?.length?meta.categories:['uncategorized'];return {...m,title:meta.title||m.modId,icon:meta.icon,projectId:meta.projectId||m.source?.projectId,categories:tags}});
 const all=[...new Set(rows.flatMap(m=>m.categories))] as string[];all.sort((a,b)=>{const ids=Object.keys(categories);return (ids.includes(a)?ids.indexOf(a):ids.length-1)-(ids.includes(b)?ids.indexOf(b):ids.length-1)});
 const filtered=rows.filter(m=>(!category||m.categories.includes(category))&&(!side||m.side===side)&&`${m.title} ${m.modId} ${m.version}`.toLowerCase().includes(query.toLowerCase()));
 const primary=(m:Json)=>m.categories.includes('library')?'library':all.find(c=>m.categories.includes(c))||'uncategorized';
 const groups=category?[category]:all.filter(c=>filtered.some(m=>primary(m)===c));
 return <div className="installed-mods"><div className="installed-toolbar"><label className="library-search"><Search size={16}/><input aria-label={t("搜索已安装 Mod")} placeholder={t("搜索已安装的名称…")} value={query} onChange={e=>setQuery(e.target.value)}/></label><Select aria-label={t("Mod 适用环境")} value={side} onChange={e=>setSide(e.target.value)}><option value="">{t("全部适用环境")}</option><option value="client">{t("客户端")}</option><option value="server">{t("服务器")}</option><option value="both">{t("双端")}</option></Select><button className="icon-button" title={t("更新分类")} aria-label={t("更新分类")} disabled={loading} onClick={()=>setRetry(n=>n+1)}>{loading?<LoaderCircle className="spin" size={15}/>:<RefreshCw size={15}/>}</button></div>
 <div className="installed-categories" role="group" aria-label={t("已安装 Mod 分类")}><button className={!category?'selected':''} aria-pressed={!category} onClick={()=>setCategory('')}>{t("全部 ")}<span>{rows.length}</span></button>{all.map(c=><button key={c} className={category===c?'selected':''} aria-pressed={category===c} onClick={()=>setCategory(c)}>{label(c)} <span>{rows.filter(m=>m.categories.includes(c)).length}</span></button>)}</div>
 {loading&&<p className="muted">{t("正在识别分类，现有 Mod 可以继续查看…")}</p>}{warning&&<p role="status" className="muted">{<ServiceMessage text={warning}/>}</p>}
 <div className="installed-summary">{t("显示 ")}{filtered.length} / {rows.length} {t(" 个 Mod ")}</div>
 {!filtered.length?<div className="empty panel"><Box size={28}/><p>{t("没有符合条件的 Mod。")}</p><button className="button" onClick={()=>{setQuery('');setSide('');setCategory('')}}>{t("清除筛选")}</button></div>:groups.map(c=><section className="installed-group" key={c}><h3>{label(c)} <span>{(category?filtered:filtered.filter(m=>primary(m)===c)).length}</span></h3><div className="panel">{(category?filtered:filtered.filter(m=>primary(m)===c)).sort((a,b)=>a.title.localeCompare(b.title)).map(m=><div className="installed-row" key={m.modId}><span className="installed-icon">{m.icon?<img src={m.icon} alt="" loading="lazy" onError={e=>{e.currentTarget.style.display='none'}}/>:<Box size={22}/>}</span><div className="installed-name"><strong>{m.title}</strong><small title={m.modId}>{m.version}</small><div className="installed-tags">{m.categories.map((tag:string)=><span key={tag}>{label(tag)}</span>)}</div></div><span className="installed-side" title={t("适用环境")}>{m.side==='client'?t("客户端"):m.side==='server'?t("服务器"):t("双端")}</span><div className="row-actions">{m.projectId&&<button className="icon-button" aria-label={t("选择 {0} 的版本",m.title)} title={t("选择版本或更新")} disabled={item.running||busy} onClick={()=>onVersion({project_id:m.projectId,title:m.title})}><RefreshCw size={16}/></button>}<button className="icon-button" aria-label={t("移除 {0}",m.title)} title={t("从实例移除")} disabled={item.running||busy} onClick={()=>onRemove(m)}><Trash2 size={16}/></button></div></div>)}</div></section>)}
 </div>
}
