import {ContentConflicts} from './ContentConflicts';
import {AppUpdates} from './AppUpdates';
import {t,getLocale,ServiceMessage,useLocale,LanguagePicker} from './i18n';
import {InstalledMods} from './InstalledMods';
import {PackExport} from './PackExport';
import {Packs} from './Packs';
import {JobProgress} from './TaskProgress';
import {Recovery} from './Recovery';
import {useHomeMemory,playedTime,recentTime} from './HomeMemory';
import {Shaders} from './Shaders';
import {Preflight} from './Preflight';
import {Diagnostics} from './Diagnostics';
import {ModUpdates} from './ModUpdates';
import {ModBrowser} from './ModBrowser';
import {Select} from './Select';
import React, {useEffect, useState, useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {invoke} from '@tauri-apps/api/core';
import {Blocks, Box, Server, HardDrive, Settings, Plus, Play, Square, Download, RefreshCw, Search, X, ArrowLeft, ChevronRight, FolderOpen, Link, Check, AlertCircle, LoaderCircle, ExternalLink, Copy, Trash2, Terminal, ShieldCheck, UserRound, ArrowUpRight, Sparkles, Map, Gamepad2} from 'lucide-react';
import './style.css';
import './desktop.css';
import './controls.css';
import './gaming.css';
import './immersive.css';
import './polish.css';
import {LobbyRoom,LobbySettings} from './Lobby';
import {Worlds} from './Worlds';
import {TrashPanel} from './Trash';
type Json = Record<string,any>;
type Item = {instance:Json;config:Json;installed:boolean;running:boolean;mods:Json[];receipt:Json|null;pack?:Json|null;published:boolean};
const api=(action:string,payload:Json={})=>invoke<any>('call',{action,payload});
const size=(n:number)=>n>1073741824?`${(n/1073741824).toFixed(2)} GB`:`${(n/1048576).toFixed(1)} MB`;
const loaderName=(i:Json)=>i.loader.kind==='vanilla'?'Vanilla':`${({neoforge:'NeoForge',fabric:'Fabric',forge:'Forge',quilt:'Quilt'} as Record<string,string>)[i.loader.kind]||i.loader.kind} ${i.loader.version}`;
function App(){
 useLocale();
 const [state,setState]=useState<Json|null>(null),[page,setPage]=useState('instances'),[selected,setSelected]=useState<string|null>(null),[tab,setTab]=useState('play'),[modal,setModal]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [versions,setVersions]=useState<Json[]>([]),[form,setForm]=useState<Json>({name:'',minecraft:'26.2',loader:'fabric',memory:4096,port:25565,install:true}),[hits,setHits]=useState<Json[]>([]),[query,setQuery]=useState(''),[searching,setSearching]=useState(false),[logs,setLogs]=useState(''),[command,setCommand]=useState(''),[device,setDevice]=useState<Json|null>(null),[clientId,setClientId]=useState(''),[modVersions,setModVersions]=useState<Json[]>([]),[project,setProject]=useState<Json|null>(null),[invitation,setInvitation]=useState('');
 const [offlineName,setOfflineName]=useState(''); const [advanced,setAdvanced]=useState(false); const [dismissedLaunch,setDismissedLaunch]=useState(''); const startAfterLogin=useRef<string|null>(null);
 const [libraryQuery,setLibraryQuery]=useState(''); const [homeSelected,setHomeSelected]=useState<string|null>(null);
 const [versionsLoading,setVersionsLoading]=useState(false),[versionsError,setVersionsError]=useState('');
 const versionRequest=useRef(0);
 const [loaderVersions,setLoaderVersions]=useState<Json[]>([]),[loadingLoader,setLoadingLoader]=useState(false),[loaderError,setLoaderError]=useState('');
 useEffect(()=>{if(modal!=='create'||form.loader==='vanilla')return;let active=true;setLoadingLoader(true);setLoaderVersions([]);setLoaderError('');api('loaders',{minecraft:form.minecraft,loader:form.loader}).then(v=>{if(active)setLoaderVersions(v)}).catch(e=>{if(active)setLoaderError(String(e))}).finally(()=>{if(active)setLoadingLoader(false)});return()=>{active=false}},[modal,form.minecraft,form.loader]);
 const refresh=async()=>{try{const [data,network,lobby]=await Promise.all([api('status'),api('peer-status'),api('lobby-status')]);setState({...data,network,lobby})}catch(e){setError(String(e))}};
 useEffect(()=>{if(state){void invoke('confirm_update_startup').catch(()=>{});}},[!!state]);
 useEffect(()=>{void refresh();const t=setInterval(refresh,1500);api('versions').then(setVersions).catch(()=>{});return()=>clearInterval(t)},[]);
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){startAfterLogin.current=null;setModal('');setDevice(null)}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[]);
 const items=(state?.instances||[]) as Item[],current=items.find(x=>x.instance.instanceId===selected),jobs=(state?.jobs||[]) as Json[],activeJobs=jobs.filter(j=>['queued','running'].includes(j.status));
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer)},[notice]);
 const seenFailures=useRef(new Set<string>()); const failuresInitialized=useRef(false);
 useEffect(()=>{if(!state)return;if(!failuresInitialized.current){jobs.filter(j=>j.status==='error').forEach(j=>seenFailures.current.add(j.id));failuresInitialized.current=true;return}const errors=jobs.filter(j=>j.status==='error'&&!seenFailures.current.has(j.id));errors.forEach(j=>seenFailures.current.add(j.id));if(errors.length)setError(errors[errors.length-1].message)},[state]);
 const jobBusy=(id?:string)=>activeJobs.some(j=>!id||j.instanceId===id);
 const run=async(action:string,payload:Json={})=>{setError('');setBusy(true);try{const r=await api(action,payload);await refresh();return r}catch(e){setError(String(e));return null}finally{setBusy(false)}};
 useEffect(()=>{if(state?.account&&startAfterLogin.current){const id=startAfterLogin.current;startAfterLogin.current=null;setModal('');void run('launch',{id})}},[state?.account?.name]);
 const latestLaunch=jobs.filter(j=>j.action==='launch'&&j.instanceId===selected).slice(-1)[0]; const launchDecision=latestLaunch?.status==='done'&&latestLaunch.result?.needsDecision&&dismissedLaunch!==latestLaunch.id?latestLaunch.result:null;
 const submit=async(action:string,payload:Json={},close=true)=>{const r=await run(action,payload);if(r&&close)setModal('');return r};
 const open=(item:Item)=>{setSelected(item.instance.instanceId);setTab('play');setError('')};
 const newItem=()=>{setForm({name:'',minecraft:versions[0]?.id||'26.2',loader:'fabric',loaderVersion:'',memory:4096,port:25565,install:true,server:page==='servers'});setModal('create')};
 const openSettings=()=>{if(!current)return;setForm({id:selected,name:current.instance.name,memory:current.instance.runtime.memoryMiB,port:current.config.port||25565,shareContent:current.config.shareContent===true,javaPath:current.config.javaPath||'',serverId:current.config.serverId||''});setModal('instance-settings')};
 const pick=async()=>{try{const path=await invoke<string|null>('pick_mod');if(path)await run('mod-local',{id:selected,path})}catch(e){setError(String(e))}};
 const folder=async(id?:string)=>{try{await invoke('open_folder',{id:id||null})}catch(e){setError(String(e))}};
 const link=async(url:string)=>{try{await invoke('open_link',{url})}catch(e){setError(String(e))}};
 const browse=()=>{setModal('mods');setError('')};
 const chooseVersion=async(p:Json)=>{const request=++versionRequest.current;setProject(p);setModVersions([]);setVersionsLoading(true);setVersionsError('');setModal('versions');try{const list=await api('mod-versions',{project:p.project_id,minecraft:current?.instance.minecraft,loader:current?.instance.loader.kind});if(request===versionRequest.current)setModVersions(list)}catch(e){if(request===versionRequest.current)setVersionsError(String(e))}finally{if(request===versionRequest.current)setVersionsLoading(false)}};
 const start=(item:Item|undefined=current)=>{if(!item)return;setSelected(item.instance.instanceId);const current=item;if(current.config.server){setForm({eula:false});setModal('eula')}else if(!state?.account){startAfterLogin.current=current.instance.instanceId;setClientId(state?.settings.clientId||'');setModal('account')}else void run('launch',{id:current.instance.instanceId})};
 useEffect(()=>{if(tab!=='logs'||!selected)return;const update=()=>api('logs',{id:selected}).then(v=>setLogs(v.text)).catch(e=>setError(String(e)));void update();const t=setInterval(update,2000);return()=>clearInterval(t)},[selected,tab]);
 useEffect(()=>{if(!device)return;let disposed=false;let timer:ReturnType<typeof setTimeout>;let interval=Math.max(5,device.interval||5);const poll=async()=>{try{const r=await api('auth-poll',{code:device.device_code});if(disposed)return;if(!r.pending){setDevice(null);setModal('');setNotice(t("微软账户已登录"));void refresh();return}if(r.slow)interval+=5;if(Date.now()>device.deadline){setDevice(null);setError(t("登录代码已过期，请重试"));return}timer=setTimeout(poll,interval*1000)}catch(e){if(!disposed){setDevice(null);setError(String(e))}}};timer=setTimeout(poll,interval*1000);return()=>{disposed=true;clearTimeout(timer)}},[device]);
 const login=async()=>{setError('');setBusy(true);try{const r=await api('auth-start');setDevice({...r,deadline:Date.now()+(r.expires_in||900)*1000})}catch(e){setError(String(e))}finally{setBusy(false)}};
 const visible=items.filter(x=>Boolean(x.config.server)===(page==='servers'));
 const filtered=visible.filter(i=>`${i.instance.name} ${i.instance.minecraft} ${loaderName(i.instance)}`.toLowerCase().includes(libraryQuery.toLowerCase()));
 const memories=useHomeMemory();
 const recent=memories.filter(m=>visible.some(i=>i.instance.instanceId===m.id)).sort((a,b)=>recentTime(b)-recentTime(a))[0];
 const featured=visible.find(i=>i.instance.instanceId===homeSelected)||visible.find(i=>i.instance.instanceId===recent?.id)||visible[0];
 const homeMemory=memories.find(m=>m.id===(current||featured)?.instance.instanceId);
 return <div className={`app ${current?'detail-mode':page==='instances'||page==='servers'?'library-mode':'management-mode'}`}><aside><div className="brand"><span className="brand-mark"><Blocks size={23}/></span>blocklink<span className="version">α</span></div><div className="workspace-label">PLAY YOUR WAY</div><nav>{[{id:'instances',icon:Box,label:t("我的游戏")},{id:'servers',icon:Server,label:t("联机大厅")},{id:'packs',icon:Box,label:t("整合包")},{id:'downloads',icon:Download,label:t("任务与下载")}].map(n=><button key={n.id} className={page===n.id?'nav active':'nav'} onClick={()=>{setPage(n.id);setSelected(null);setLibraryQuery('')}}><n.icon size={19}/>{n.label}{n.id==='downloads'&&activeJobs.length>0&&<b>{activeJobs.length}</b>}</button>)}</nav><div className="sidebar-bottom"><AppUpdates/><div className="native-status"><span className={`dot ${state?'':'amber'}`}/>{state?t("后台已连接"):t("连接中")}<small>{state?.platform||t("正在连接")}</small></div><button className="nav" onClick={()=>{setClientId(state?.settings.clientId||'');setModal('settings')}}><Settings size={18}/>{t("启动器设置")}</button><button className="account" onClick={()=>{setClientId(state?.settings.clientId||'');setModal('account')}}><span className="avatar"><UserRound size={18}/></span><span>{state?.account?.name||t("选择玩家档案")}<small>{state?.account?.offline?t("离线档案"):state?.account?'Minecraft Java Edition':t("微软账户 / 离线游玩")}</small></span><ChevronRight size={16}/></button></div></aside>
 <main><header><span>Blocklink <span className="slash">/</span> {page==='servers'?t("联机大厅"):page==='store'?t("存储管理"):page==='downloads'?t("任务与下载"):page==='packs'?t("整合包"):t("我的游戏")}{current&&<><span className="slash">/</span>{current.instance.name}</>}</span><div className="header-right"><span className="tag">Java Edition</span><button className="icon-button" title={t("刷新")} onClick={refresh}><RefreshCw size={16}/></button></div></header>
 <div className="content">{error&&<div role="alert" className="alert"><AlertCircle size={18}/><span>{<ServiceMessage text={error}/>}</span><button onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div className="success-toast" role="status" aria-live="polite"><Check size={17}/><span>{<ServiceMessage text={notice}/>}</span><button aria-label={t("关闭提示")} onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {!state?<div className="empty"><LoaderCircle className="spin"/><h2>{t("正在准备你的游戏")}</h2><p>{t("马上就好。")}</p></div>:current?<>
 <button className="back" onClick={()=>setSelected(null)}><ArrowLeft size={15}/>{t("返回")}{current.config.server?t("服务器"):t("我的游戏")}</button>
 <section className={`game-scene detail-scene ${current.config.server?'scene-server':''}`}>
 <div className="scene-tools"><button className="scene-tool" title={t("打开游戏文件夹")} aria-label={t("打开游戏文件夹")} onClick={()=>folder(selected!)}><FolderOpen size={18}/></button><button className="scene-tool" title={t("游戏设置")} aria-label={t("游戏设置")} onClick={openSettings}><Settings size={18}/></button><button className="scene-tool" title={t("删除游戏")} aria-label={t("删除游戏")} disabled={current.running||jobBusy()} onClick={()=>{setForm(current);setModal('delete')}}><Trash2 size={18}/></button></div>
 <div className="scene-copy"><span className="scene-kicker">{current.config.server?'BETTER TOGETHER':'MINECRAFT · JAVA EDITION'}</span><h1>{current.instance.name}</h1><p>Minecraft {current.instance.minecraft}<span className="scene-divider">/</span>{current.mods.length} {t(" 个 Mod")}<span className="scene-divider">/</span>{current.config.server?t("本机托管"):current.instance.loader.kind==='vanilla'?t("原版体验"):t("模组世界")}</p>
 <div className="scene-launch">{current.running?<button className="button danger" onClick={()=>run('stop',{id:selected})}><Square size={18}/>{t("停止")}{current.config.server?t("服务器"):t("游戏")}</button>:<button className="button primary play-cta" disabled={jobBusy(selected!)} onClick={()=>start()}>{jobBusy(selected!)?<LoaderCircle size={21} className="spin"/>:<Play size={21} fill="currentColor"/>}{jobBusy(selected!)?t("正在准备…"):current.config.server?t("启动服务器"):(current.config.peerInvitation||current.config.lobbyInvitation)?t("同步并加入"):t("开始游戏")}</button>}<span>{current.running?t("正在冒险中"):current.installed?t("准备好了，随时出发"):t("首次启动将自动下载所需文件")}</span></div></div></section>
 {current.pack&&<p className="pack-caption">{current.pack.name} · {current.pack.version}</p>}
 {advanced&&<div className="info-strip"><span>{loaderName(current.instance)}</span><span>{current.config.server?t("端口 {0}",current.config.port):t("运行详情")}</span></div>}
 {activeJobs.filter(j=>j.instanceId===selected).map(j=><JobProgress key={j.id} job={j} onRefresh={refresh}/>)}
 <ContentConflicts key={selected} item={current} jobs={jobs} onRefresh={refresh}/>
 <Recovery item={current} jobs={jobs} onStart={()=>start()} onSettings={openSettings} onRestore={()=>{setAdvanced(true);setTab('updates')}} onLogs={()=>{setAdvanced(true);setTab('logs')}} onRefresh={refresh}/>

 {current.config.server&&<div className="sharing-row"><span><Link size={15}/>{t("邀请朋友联机 · 自动同步 Mods")}</span><button className="button" disabled={!current.published} onClick={()=>{setForm({mode:'peer',host:state.settings.sharing?.host||'',port:state.settings.sharing?.port||25566,relay:state.settings.peerRelay||''});setInvitation('');setModal('share')}}>{t("邀请朋友")}</button></div>}
 {current.config.lobbyInvitation&&<div className="sharing-row"><span><ShieldCheck size={15}/>{current.config.remoteName}{t("的房间")}</span><button className="button" disabled={current.running||jobBusy(selected!)} onClick={()=>run('sync',{id:selected})}>{t("立即同步")}</button></div>} {current.config.peerInvitation&&<div className="sharing-row"><span><ShieldCheck size={15}/>{t("已配对：")}{current.config.remoteName}{t("的房间")}</span><button className="button" disabled={current.running||jobBusy(selected!)} onClick={()=>run('sync',{id:selected})}>{t("立即同步")}</button></div>}
 {current.config.peerInvitation&&state.network?.bridges?.find((b:Json)=>b.id===selected)&&<div className="hint compact"><p>{t("本机游戏入口：")}{state.network.bridges.find((b:Json)=>b.id===selected).address}。{state.network.connections?.filter((c:Json)=>c.id===selected).map((c:Json,n:number)=><span key={n}> {c.route==='direct'?t("已直连"):c.route==='relay'?t("中继连接"):t("正在连接")} · {c.latencyMs??'—'} ms。</span>)}{t("点击「同步并加入」会自动连接；服务器仍执行自己的正版验证。")}</p></div>}
 {current.config.remoteInvitation&&<div className="sharing-row"><span><ShieldCheck size={15}/>{t("已配对：")}{current.config.remoteName} {t(" · 进入前自动更新")}</span><button className="button" disabled={current.running||jobBusy(selected!)} onClick={()=>run('sync',{id:selected})}>{t("立即同步")}</button></div>}
 <div className="tabs">{[{id:'play',name:t("概览")},{id:'mods',name:t("模组")},{id:'worlds',name:t("世界与存档")},...(!current.config.server?[{id:'shaders',name:t("光影")}]:[]),...(advanced?[{id:'updates',name:t("更新与恢复")},{id:'install',name:t("安装与运行")},{id:'logs',name:current.config.server?t("服务器控制台"):t("运行日志")}]:[])].map(t=><button aria-pressed={tab===t.id} className={tab===t.id?'selected':''} onClick={()=>setTab(t.id)} key={t.id}>{t.name}</button>)}<button className="text-link advanced-toggle" onClick={()=>{setAdvanced(!advanced);if(advanced)setTab('play')}}>{advanced?t("收起高级管理"):t("高级管理")}</button></div>

{launchDecision&&<section className="panel settings-card" role="alert"><h2>{<ServiceMessage text={launchDecision.title}/>}</h2><p>{<ServiceMessage text={launchDecision.message}/>}</p>{launchDecision.items?.map((x:Json)=><p key={x.name}><strong>{x.name}</strong> · {<ServiceMessage text={x.reason}/>}</p>)}{launchDecision.details&&<details><summary>{t("技术详情")}</summary><p>{<ServiceMessage text={launchDecision.details}/>}</p></details>}<div className="actions"><button className="button" disabled={jobBusy(selected!)} onClick={()=>setDismissedLaunch(latestLaunch.id)}>{t("先不启动")}</button><button className="button primary" disabled={jobBusy(selected!)} onClick={()=>run('launch',{id:selected,...(launchDecision.kind==='mods'?{acceptPlan:launchDecision.planId}:{continueWithoutShader:launchDecision.planId})})}>{launchDecision.kind==='mods'?t("关闭这些内容并开始游戏"):t("使用普通画面开始游戏")}</button></div></section>}
{tab==='play'&&<div className="play-overview"><div className="section-heading"><div><h2>{t("让这个世界更像你")}</h2><p>{t("探索新内容，或继续你留下的故事。")}</p></div></div><div className="game-shortcuts"><button onClick={()=>setTab('mods')}><span className="shortcut-icon"><Box size={24}/></span><strong>{t("探索模组")}</strong><small>{current.mods.length?t("已添加 {0} 个，发现更多玩法",current.mods.length):t("从新的玩法开始")}</small><ChevronRight size={18}/></button><button onClick={()=>setTab('worlds')}><span className="shortcut-icon amber-icon"><Map size={24}/></span><strong>{t("世界与存档")}</strong><small>{t("继续冒险 · 导入旧世界")}</small><ChevronRight size={18}/></button><button onClick={()=>{if(current.config.server){setAdvanced(true);setTab('logs')}else setTab('shaders')}}><span className="shortcut-icon violet-icon">{current.config.server?<Terminal size={24}/>:<Sparkles size={24}/>}</span><strong>{current.config.server?t("服务器控制台"):t("光影与画面")}</strong><small>{current.config.server?t("查看运行情况和发送命令"):t("换一种光，看同一个世界")}</small><ChevronRight size={18}/></button></div><div className="quiet-reassurance"><ShieldCheck size={17}/><span>{t("运行环境自动准备 · 修改模组前备份存档")}</span><button className="text-link" onClick={()=>{setAdvanced(true);setTab('install')}}>{t("查看运行详情 ")}<ChevronRight size={14}/></button></div></div>}
{tab==='worlds'&&<Worlds key={selected} item={current} account={state.account} jobs={jobs} onError={setError} onOpen={id=>{setPage('servers');setSelected(id);setTab('worlds');void refresh()}}/>}
 {tab==='shaders'&&<Shaders key={selected} item={current} jobs={jobs} onRefresh={refresh}/>}
 {tab==='updates'&&<ModUpdates item={current} jobs={jobs} onRefresh={refresh}/>} 
 {tab==='mods'&&<><div className="section-heading"><div><h2>{t("已安装的 Mod ")}<span className="count">{current.mods.length}</span></h2><p></p></div><div className="actions">{current.config.server?<button className="button" disabled={current.running||jobBusy(selected!)} onClick={()=>run('publish',{id:selected})}><ArrowUpRight size={16}/>{t("发布环境")}</button>:current.config.serverId&&<button className="button" disabled={current.running||jobBusy(selected!)} onClick={()=>run('sync',{id:selected})}><RefreshCw size={16}/>{t("同步服务器")}</button>}<button className="button" disabled={current.running||jobBusy(selected!)||current.instance.loader.kind==='vanilla'} onClick={pick}><FolderOpen size={16}/>{t("从文件添加")}</button><button className="button primary" disabled={current.running||current.instance.loader.kind==='vanilla'} onClick={browse}><Plus size={17}/>{t("添加 Mod")}</button></div></div>
 {current.mods.length===0?<div className="empty panel"><Box size={35}/><h3>{current.instance.loader.kind!=='vanilla'?t("给这个世界添点新东西"):t("纯粹的 Minecraft")}</h3><p>{current.instance.loader.kind!=='vanilla'?t("从 Modrinth 安装，或导入匹配 Loader 的本地 Mod。"):t("Vanilla 不加载 Mod。创建带 模组支持 的实例即可管理 Mods。")}</p>{current.instance.loader.kind!=='vanilla'&&<button className="button" onClick={browse}>{t("浏览兼容 Mods ")}<ChevronRight size={15}/></button>}</div>:<InstalledMods key={selected} item={current} busy={jobBusy(selected!)} onRemove={m=>{void run('mod-remove',{id:selected,modId:m.modId})}} onVersion={chooseVersion}/>}

 {current.config.server&&<div className="hint"><ShieldCheck size={18}/><div>{t("服务器环境由你发布")}<p>{t("停止服务器后修改 Mods，再发布或启动。游戏实例绑定后会在启动前自动同步；客户端专用 Mods 会保留。")}</p></div></div>}</>}
 {tab==='logs'&&<Diagnostics key={selected} id={selected!}/>}
 {tab==='install'&&<Preflight key={selected} id={selected!} onRepair={()=>setTab('updates')}/>}
 {tab==='install'&&<div className="install-grid">{!current.config.server&&<PackExport id={selected!} busy={current.running||jobBusy()} onRefresh={refresh}/>}<section className="panel settings-card"><Download size={24}/><h2>{t("自动准备运行环境")}</h2><p>{t("根据当前系统和游戏版本下载 Java、Minecraft、资源文件与 ")}{current.instance.loader.kind!=='vanilla'?loaderName(current.instance):t("原版依赖")}。</p><div className="setting-row"><span>Java</span><strong>{current.config.javaPath?t("使用指定 Java"):t("自动下载并管理")}</strong></div><div className="setting-row"><span>Minecraft</span><strong>{current.instance.minecraft}</strong></div><div className="setting-row"><span>{t("模组支持")}</span><strong>{loaderName(current.instance)}</strong></div><button className="button primary" disabled={current.running||jobBusy(selected!)} onClick={()=>run('install',{id:selected})}><Download size={17}/>{current.installed?t("检查并修复安装"):t("下载并安装")}</button><small>{t("已校验的下载会复用；失败后可以重试。")}</small></section><section className="panel settings-card"><Link size={24}/><h2>{t("独立世界，共享文件")}</h2><p>{t("复制实例会复用 Mod 仓库，创建独立的游戏目录。可选择同时复制世界、配置与资源包。副本首次启动会自动准备游戏文件，联机邀请不会复制。")}</p><button className="button" disabled={current.running} onClick={()=>run('duplicate',{id:selected})}><Copy size={16}/>{t("复制 Mod 环境为新实例")}</button><button className="button" disabled={current.running||jobBusy()} onClick={()=>run('duplicate',{id:selected,includeWorlds:true})}>{t("复制完整实例（含世界）")}</button><button className="button" disabled={jobBusy(selected!)} onClick={()=>run('verify',{id:selected})}><ShieldCheck size={16}/>{t("校验 Mods 完整性")}</button><button className="button" onClick={()=>folder(selected!)}><FolderOpen size={16}/>{t("打开游戏目录")}</button></section></div>}
 {tab==='logs'&&<><div className="section-heading"><div><h2>{current.config.server?t("服务器控制台"):t("游戏输出")}</h2><p>{t("关闭 Blocklink 窗口不会停止后台托管的服务器。")}</p></div>{current.running&&<button className="button danger" onClick={()=>{setModal('force')}}>{t("强制结束")}</button>}</div><pre className="console">{logs||t("等待日志…")}</pre>{current.config.server&&<form className="console-input" onSubmit={e=>{e.preventDefault();void run('console',{id:selected,command});setCommand('')}}><Terminal size={18}/><input placeholder={t("输入服务器命令，例如 list")} value={command} onChange={e=>setCommand(e.target.value)} disabled={!current.running}/><button className="button" disabled={!current.running||!command.trim()}>{t("发送")}</button></form>}</>}
 </>:page==='packs'?<Packs installed={items} jobs={jobs} onRefresh={refresh} onOpen={id=>{setPage('instances');setSelected(id);setTab('play');void refresh()}}/>:page==='store'?<><button className="back" onClick={()=>{setPage('instances');setClientId(state?.settings.clientId||'');setModal('settings')}}><ArrowLeft size={15}/>{t("返回设置")}</button><div className="page-heading"><div><h1>{t("存储管理")}</h1><p>{t("文件会自动复用，不需要手动整理。")}</p></div></div><section className="panel settings-card"><h2>{t("模组占用空间")}</h2><strong style={{fontSize:30}}>{size(state.store.bytes)}</strong><p>{t("这里只统计模组文件，不包含游戏、世界和备份。")}</p><button className="button" onClick={()=>folder()}><FolderOpen size={17}/>{t("打开启动器数据文件夹")}</button></section></>:page==='downloads'?<><div className="page-heading"><div><h1>{t("任务与下载")}</h1><p>{t("安装、校验和同步的真实执行结果。")}</p></div></div><div className="panel jobs">{jobs.length===0?<div className="empty"><Download size={32}/><h3>{t("一切就绪")}</h3><p>{t("安装任务会显示在这里。")}</p></div>:[...jobs].reverse().map(j=><div key={j.id}><h3>{({'create':t("创建与安装"),'install':t("安装运行环境"),'launch':t("启动游戏"),'pack-install':t("安装整合包"),'pack-import':t("导入整合包")} as Json)[j.action]||j.action}</h3><JobProgress job={j} onRefresh={refresh}/>{j.status==='done'&&j.result?.id&&j.action.startsWith('pack-')&&<button className="button" onClick={()=>{setPage('instances');setSelected(j.result.id)}}>{t("进入我的游戏")}</button>}</div>)}</div></>:<>
 <div className="launcher-home">
 <div className="game-wordmark"><span>{page==='servers'?'PLAY TOGETHER':'BLOCKLINK LAUNCHER'}</span><h1>MINECRAFT</h1><p>{page==='servers'?t("和朋友，一起创造世界"):'J A V A   E D I T I O N'}</p>{page!=='servers'&&homeMemory?.world&&<div className="home-world"><span>{t("最近的世界")}</span><strong>{homeMemory.world.name}</strong><small>{t("上次游玩 · ")}{playedTime(homeMemory.world.lastPlayed)}</small></div>}{page!=='servers'&&!homeMemory?.world&&homeMemory?.lastLaunchedAt&&<div className="home-world"><small>{t("上次启动 · ")}{playedTime(homeMemory.lastLaunchedAt)}</small></div>}</div>
 <div className="world-picker"><div className="picker-heading"><div><h2>{page==='servers'?t("选择服务器"):t("选择你的冒险")}</h2><span>{visible.length} {t(" 个")}{page==='servers'?t("服务器"):t("游戏")}</span></div><div className="picker-tools"><label className="library-search"><Search size={16}/><input aria-label={t("搜索实例")} placeholder={t("搜索…")} value={libraryQuery} onChange={e=>setLibraryQuery(e.target.value)}/>{libraryQuery&&<button className="icon-button" aria-label={t("清除搜索")} onClick={()=>setLibraryQuery('')}><X size={14}/></button>}</label><button className="button" onClick={newItem}><Plus size={17}/>{page==='servers'?t("新建服务器"):t("新建游戏")}</button>{page==='instances'&&<button className="button" onClick={()=>{setForm({name:'',invitation:''});setModal('join')}}><Link size={17}/>{t("加入朋友")}</button>}</div></div>
 <div className="world-carousel">{filtered.map((i,index)=><article className={`world-tile cover-${index%3} ${featured?.instance.instanceId===i.instance.instanceId?'chosen':''}`} key={i.instance.instanceId}><button className="world-choice" aria-pressed={featured?.instance.instanceId===i.instance.instanceId} aria-label={t("选择 {0}",i.instance.name)} onClick={()=>setHomeSelected(i.instance.instanceId)}><span className="tile-cover">{memories.find(m=>m.id===i.instance.instanceId)?.cover&&<img alt="" src={memories.find(m=>m.id===i.instance.instanceId)?.cover||undefined} onError={e=>{e.currentTarget.style.display='none'}}/>}</span><span className="tile-description"><strong title={i.instance.name}>{i.instance.name}</strong><small>{i.instance.minecraft} · {loaderName(i.instance).split(' ')[0]} · {i.mods.length} Mods</small></span>{featured?.instance.instanceId===i.instance.instanceId&&<Check className="chosen-check" size={16}/>}</button><button className="tile-settings" aria-label={t("管理 {0}",i.instance.name)} onClick={()=>open(i)}><Settings size={16}/></button></article>)}{!filtered.length&&<div className="carousel-empty"><Gamepad2 size={25}/><span>{visible.length?t("没有找到这个世界，试试其他名称。"):t("还没有游戏，创建你的第一场冒险。")}</span>{!visible.length&&<button className="button" onClick={newItem}><Plus size={16}/>{t("创建游戏")}</button>}</div>}</div>
 </div>
 <div className="home-download-progress">{activeJobs.filter(j=>j.instanceId===featured?.instance.instanceId).map(j=><JobProgress key={j.id} job={j} onRefresh={refresh}/>)}</div><div className="launch-dock"><div className="dock-selection"><Gamepad2 size={25}/><div><strong>{featured?.instance.name||t("准备出发")}</strong><small>{featured?`${featured.instance.minecraft} · ${featured.running?t("正在运行"):jobBusy(featured.instance.instanceId)?t("正在准备"):featured.installed?t("已就绪"):t("首次启动自动安装")}`:t("Java、游戏与运行环境自动准备")}</small></div></div><div className="dock-play">{featured?.running?<button className="button danger" onClick={()=>run('stop',{id:featured.instance.instanceId})}><Square size={20}/>{t("停止")}{featured.config.server?t("服务器"):t("游戏")}</button>:<button className="button primary" disabled={featured&&(jobBusy(featured.instance.instanceId)||busy)} onClick={()=>featured?start(featured):newItem()}><Play size={23} fill="currentColor"/>{featured?jobBusy(featured.instance.instanceId)?t("正在准备…"):featured.config.server?t("启动服务器"):t("开始游戏"):t("创建游戏")}</button>}</div><div className="dock-manage">{featured&&<button className="button" onClick={()=>open(featured)}><Box size={17}/>{t("模组与世界")}<ChevronRight size={16}/></button>}<small><ShieldCheck size={12}/>{t("自动准备 · 存档独立")}</small></div></div>
 </div>
 </>}
 </div>{activeJobs.length>0&&page!=='downloads'&&<button className="task-bar" onClick={()=>{setSelected(null);setPage('downloads')}}><LoaderCircle className="spin" size={16}/>{activeJobs[0].message}<span>{activeJobs.length} {t(" 个任务")}<ChevronRight size={16}/></span></button>}<footer className="desktop-status"><span><span className={`dot ${state?'':'amber'}`}/>{state?t("本地服务已连接"):t("正在连接本地服务")}</span><span>{items.filter(i=>i.running).length} {t(" 个运行中")}</span><span className="status-platform">Blocklink 0.1.0 · {state?.platform||'—'}</span></footer></main>
 {modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget){startAfterLogin.current=null;setModal('');setDevice(null)}}}><section className={`dialog ${(modal==='mods'||modal==='versions')?'wide':''}`} role="dialog" aria-modal="true"><button className="dialog-close icon-button" aria-label={t("关闭")} onClick={()=>{startAfterLogin.current=null;setModal('');setDevice(null)}}><X size={20}/></button>
 {(modal==='delete'||modal==='trash')&&<TrashPanel item={modal==='delete'?form:undefined} jobs={jobs} onError={setError} onDeleted={()=>{setSelected(null);setModal('');setNotice(t("已永久删除"));void refresh()}}/>}
 {modal==='create'&&<><h2>{form.server?t("创建服务器"):t("添加游戏")}</h2><p>{t("选择你想玩的版本，运行环境会自动安装。")}</p><form onSubmit={e=>{e.preventDefault();void submit('create',form)}}><label>{t("名称")}<input autoFocus required maxLength={80} placeholder={form.server?t("朋友们的生存服"):t("例如：青苔原野")} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="form-grid"><label>{t("Minecraft 版本")}<Select value={form.minecraft} onChange={e=>setForm({...form,minecraft:e.target.value,loaderVersion:''})}>{[...new Set([...versions.map(v=>v.id),'26.2','26.1.2','1.21.1','1.20.1'])].map(v=><option key={v}>{v}</option>)}</Select></label><label>{t("模组支持")}<Select value={form.loader} onChange={e=>setForm({...form,loader:e.target.value,loaderVersion:''})}><option value="fabric">Fabric</option><option value="neoforge">NeoForge</option><option value="forge">Forge</option><option value="quilt">Quilt</option><option value="vanilla">{t("Vanilla · 原版")}</option></Select></label></div><p>{t("选择游戏版本后，会自动匹配可用的模组支持。")}</p>{form.loader!=='vanilla'&&<label>{t("模组支持版本")}<Select disabled={loadingLoader} value={form.loaderVersion||''} onChange={e=>setForm({...form,loaderVersion:e.target.value})}><option value="">{loadingLoader?t("正在查询兼容版本…"):t("自动选择最新稳定版")}</option>{loaderVersions.map(v=><option key={v.loader.version} value={v.loader.version}>{v.loader.version}{v.loader.stable?'':t(" · 测试版")}</option>)}</Select>{loaderError&&<span role="alert">{loaderError}</span>}{!loadingLoader&&!loaderError&&!loaderVersions.length&&<span>{t("此 Minecraft 版本没有可用的 ")}{form.loader}{t("。请更换游戏版本或 Loader。")}</span>}</label>}<div className="form-grid"><label>{t("游戏内存")}<Select value={form.memory} onChange={e=>setForm({...form,memory:Number(e.target.value)})}>{[2048,4096,6144,8192,12288,16384].map(m=><option value={m} key={m}>{m/1024} GB</option>)}</Select></label>{form.server&&<label>{t("服务器端口")}<input type="number" min={1024} max={65535} value={form.port} onChange={e=>setForm({...form,port:Number(e.target.value)})}/></label>}</div><div className="auto-install"><Download size={21}/><div><strong>{t("自动下载 Java、游戏与 Loader")}</strong><small>{t("选择好版本，剩下的自动完成")}</small></div></div><label className="checkbox"><input type="checkbox" checked={form.install} onChange={e=>setForm({...form,install:e.target.checked})}/>{t("创建后立即安装")}</label><div className="dialog-footer"><button type="button" className="button" onClick={()=>setModal('')}>{t("取消")}</button><button className="button primary" disabled={busy||!form.name.trim()||(form.loader!=='vanilla'&&(loadingLoader||!!loaderError||!loaderVersions.some(v=>form.loaderVersion?v.loader.version===form.loaderVersion:v.loader.stable)))}><Plus size={17}/>{t("创建")}{form.install?t("并安装"):''}</button></div></form></>}
 {modal==='instance-settings'&&<><h2>{t("游戏设置")}</h2><form onSubmit={e=>{e.preventDefault();void submit('configure',form)}}><label>{t("名称")}<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>{t("内存（MB）")}<input type="number" min={512} max={131072} value={form.memory} onChange={e=>setForm({...form,memory:Number(e.target.value)})}/></label><label>{t("Java 路径（留空自动管理）")}<input placeholder={t("自动下载匹配的 Java")} value={form.javaPath} onChange={e=>setForm({...form,javaPath:e.target.value})}/></label>{current?.config.server?<label>{t("服务器端口")}<input type="number" min={1024} max={65535} value={form.port} onChange={e=>setForm({...form,port:Number(e.target.value)})}/></label>:<label>{t("启动前同步服务器")}<Select value={form.serverId} onChange={e=>setForm({...form,serverId:e.target.value})}><option value="">{t("不绑定，独立管理")}</option>{items.filter(i=>i.config.server&&i.instance.minecraft===current?.instance.minecraft&&loaderName(i.instance)===loaderName(current!.instance)).map(i=><option key={i.instance.instanceId} value={i.instance.instanceId}>{i.instance.name}</option>)}</Select><small>{t("仅显示游戏与 模组支持版本一致的服务器。发布后的更新会自动同步。")}</small></label>}<>{current?.config.server&&<label><input type="checkbox" checked={form.shareContent===true} onChange={e=>setForm({...form,shareContent:e.target.checked})}/>{t("同步配置与脚本")}<small>{t("向朋友发布 config、defaultconfigs、kubejs 和 scripts。请先移除其中的密码或私人信息；发布后，朋友启动前会自动同步。")}</small></label>}</><div className="dialog-footer"><button className="button primary" disabled={busy||current?.running}>{t("保存设置")}</button></div></form></>}
 {(modal==='mods'||modal==='versions')&&current&&<div hidden={modal!=='mods'}><ModBrowser item={current} onChoose={chooseVersion}/></div>}
 {modal==='versions'&&<><button className="back" onClick={()=>setModal('mods')}><ArrowLeft size={15}/>{t("返回浏览")}</button><h2>{project?.title}</h2><p>{t("选择版本，所需内容会一起安装。")}</p><div className="version-list">{versionsLoading?<p><LoaderCircle className="spin" size={15}/> {t(" 正在读取兼容版本…")}</p>:versionsError?<div role="alert"><p>{t("版本加载失败，请重试。")}</p><button className="button" onClick={()=>project&&chooseVersion(project)}>{t("重试")}</button></div>:modVersions.length===0?<p>{t("此 Mod 暂无适用于当前游戏版本和 Loader 的版本。")}</p>:modVersions.slice(0,40).map(v=><button key={v.id} onClick={()=>submit('mod-add',{id:selected,project:project?.project_id,version:v.id})} disabled={busy||current?.running}><span><strong>{v.version_number}</strong><small>{({release:t("正式版"),beta:t("测试版"),alpha:t("预览版")} as Json)[v.version_type]||v.version_type} · {new Date(v.date_published).toLocaleDateString(getLocale())} · {(v.files||[]).find((f:Json)=>f.primary)?.size?size((v.files||[]).find((f:Json)=>f.primary).size):''}</small></span><Download size={18}/></button>)}</div></>}
 {(modal==='account'||modal==='settings')&&<><h2>{modal==='settings'?t("启动器设置"):t("选择你的玩家")}</h2>
 {modal==='settings'?<><LanguagePicker/><button className="settings-entry" onClick={()=>setModal('account')}><UserRound size={22}/><span><strong>{t("玩家档案")}</strong><small>{state?.account?.name||t("还没有选择玩家")}</small></span><ChevronRight size={17}/></button><button className="settings-entry" onClick={()=>{setSelected(null);setPage('store');setModal('')}}><HardDrive size={22}/><span><strong>{t("存储空间")}</strong><small>{t("查看占用，清理不再需要的下载")}</small></span><ChevronRight size={17}/></button><details className="advanced-settings"><summary>{t("高级设置")}</summary><label>{t("Microsoft 应用 Client ID")}<input value={clientId} placeholder={t("Blocklink 的应用注册 ID")} onChange={e=>setClientId(e.target.value)}/></label><button className="button" disabled={busy} onClick={async()=>{const r=await run('settings',{clientId});if(r)setNotice(t("登录配置正在保存"))}}>{t("保存登录配置")}</button><LobbySettings url={state?.settings.lobbyUrl||''} onSaved={refresh}/><button className="button" onClick={()=>folder()}><FolderOpen size={16}/>{t("打开数据目录")}</button>{state?.settings.sharing?.enabled&&<button className="button" onClick={()=>run('sharing-stop')}>{t("关闭全部 HTTPS 共享")}</button>}</details></>:<>
 {state?.account&&<div className="account-card"><UserRound size={30}/><div><strong>{state.account.name}</strong><p>{state.account.offline?t("本地玩家"):t("微软账户")}</p></div><button className="button" onClick={()=>submit('logout')}>{t("退出")}</button></div>}
 <section className="profile-option"><h3>{t("微软账户")}</h3><p>{state?.settings.clientId?t("登录后可加入正版服务器。"):t("微软登录暂未开放，可以先使用本地玩家。")}</p>{device?<div className="device"><p>{t("在微软页面输入这段代码：")}</p><strong>{device.user_code}</strong><button className="button primary" onClick={()=>link(device.verification_uri)}><ExternalLink size={17}/>{t("打开微软登录")}</button><small><LoaderCircle className="spin" size={14}/>{t("登录完成后自动返回")}</small><button className="text-link" onClick={()=>setDevice(null)}>{t("取消登录")}</button></div>:state?.settings.clientId&&(!state?.account||state.account.offline)&&<button className="button full" disabled={busy} onClick={login}>{t("使用微软账户登录")}</button>}</section>
 <section className="profile-option"><h3>{t("本地玩家")}</h3><p>{t("适合单人游玩，无法加入要求正版验证的服务器。")}</p><label>{t("玩家名称")}<input value={offlineName} placeholder={state?.settings.offlineName||t("例如 Steve")} maxLength={16} onChange={e=>setOfflineName(e.target.value)} autoComplete="off"/></label><small>{t("1–16 位字母、数字或下划线。请保持原来的名字，以便继续使用原有背包。")}</small><button className="button primary full" disabled={busy||!/^[A-Za-z0-9_]{1,16}$/.test(offlineName||state?.settings.offlineName||'')} onClick={()=>submit('offline-profile',{name:offlineName||state?.settings.offlineName})}>{t("使用这个玩家")}</button></section></>}</>}

 {modal==='eula'&&<><h2>{t("启动 ")}{current?.instance.name}</h2><p>{t("首次运行会下载服务器依赖并创建世界。服务器将在后台继续运行。")}</p><button className="text-link" onClick={()=>link('https://www.minecraft.net/eula')}>{t("阅读 Minecraft EULA ")}<ExternalLink size={14}/></button><label className="checkbox"><input type="checkbox" checked={form.eula} onChange={e=>setForm({...form,eula:e.target.checked})}/>{t("我已阅读并同意 Minecraft EULA")}</label><div className="dialog-footer"><button className="button primary" disabled={!form.eula||busy} onClick={()=>submit('launch',{id:selected,eula:true})}><Play size={16}/>{t("启动服务器")}</button></div></>}
 {modal==='force'&&<><h2>{t("强制结束进程？")}</h2><p>{t("尚未保存的世界进度可能丢失。服务器正常退出应使用“停止服务器”。")}</p><div className="dialog-footer"><button className="button" onClick={()=>setModal('')}>{t("取消")}</button><button className="button danger" onClick={()=>submit('stop',{id:selected,force:true})}>{t("强制结束")}</button></div></>}
 {modal==='share'&&<LobbyRoom id={selected!} session={state?.lobby?.sessions?.find((s:Json)=>s.id===selected)} configured={!!state?.settings.lobbyUrl} onRefresh={refresh}/> }
 {modal==='join'&&<><h2>{t("加入朋友的房间")}</h2><p>{t("粘贴朋友发来的邀请，自动准备相同的玩法。")}</p><form onSubmit={e=>{e.preventDefault();void submit('remote-join',form)}}><label>{t("游戏名称（可选）")}<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>{t("Blocklink 房间邀请")}<textarea autoFocus required placeholder="https://…/invite/…#…" value={form.invitation} onChange={e=>setForm({...form,invitation:e.target.value})}/></label><div className="dialog-footer"><button className="button primary" disabled={busy||!form.invitation.trim()}><Link size={16}/>{t("加入房间")}</button></div></form></>}
 {error&&<div className="dialog-error" role="alert">{<ServiceMessage text={error}/>}</div>}
 </section></div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
