import {t,getLocale,ServiceMessage} from './i18n';
import React,{useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {Search,FolderOpen,Package,Download,ArrowLeft,LoaderCircle} from 'lucide-react';
import {Select} from './Select';
import {JobProgress} from './TaskProgress';
import './packs.css';
type Json=Record<string,any>;
const categoryLabels:Record<string,string>={adventure:'冒险探索',challenging:'硬核挑战',combat:'战斗',kitchen_sink:'综合玩法','kitchen-sink':'综合玩法',lightweight:'轻量体验',magic:'魔法',multiplayer:'多人联机',optimization:'性能优化',quests:'任务剧情',technology:'科技自动化','vanilla-like':'原版增强'};
const api=(action:string,payload:Json={})=>invoke<any>('call',{action,payload});
export function Packs({jobs,onRefresh,onOpen,installed=[]}:{jobs:Json[];installed?:Json[];onRefresh:()=>void;onOpen:(id:string)=>void}){
 const [query,setQuery]=useState(''),[hits,setHits]=useState<Json[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [project,setProject]=useState<Json|null>(null),[versions,setVersions]=useState<Json[]>([]),[version,setVersion]=useState(''),[local,setLocal]=useState<Json|null>(null),[name,setName]=useState(''),[optional,setOptional]=useState(true),[pending,setPending]=useState(false),[jobId,setJobId]=useState('');
 const [category,setCategory]=useState(''),[minecraft,setMinecraft]=useState(''),[loader,setLoader]=useState(''),[sort,setSort]=useState('downloads'),[categories,setCategories]=useState<string[]>([]),[gameVersions,setGameVersions]=useState<Json[]>([]),[submitted,setSubmitted]=useState(''),[showBeta,setShowBeta]=useState(false),[versionGame,setVersionGame]=useState(''),[versionLoader,setVersionLoader]=useState('');
 const sequence=useRef(0);const selectionSequence=useRef(0);const currentJob=jobs.find(j=>j.id===jobId);const locked=pending||['queued','running'].includes(currentJob?.status);
 const search=async(page=0,term=submitted)=>{const seq=++sequence.current;setLoading(true);setError('');try{const r=await api('pack-search',{query:term,offset:page,category,minecraft,loader,index:sort});if(sequence.current===seq){setHits(r.hits);setTotal(r.total_hits);setOffset(page)}}catch(e){if(sequence.current===seq){setHits([]);setError(String(e))}}finally{if(sequence.current===seq)setLoading(false)}};
 useEffect(()=>{void search();return()=>{sequence.current++}},[submitted,category,minecraft,loader,sort]);
 useEffect(()=>{api('pack-categories').then(r=>setCategories(r.map((t:Json)=>t.name))).catch(()=>setCategories(['adventure','optimization','technology','magic','quests']));api('versions').then(setGameVersions).catch(()=>{});return()=>{selectionSequence.current++}},[]);
 const matching=versions.filter(v=>(!versionGame||v.game_versions?.includes(versionGame))&&(!versionLoader||v.loaders?.includes(versionLoader))&&(showBeta||v.version_type==='release'));
 useEffect(()=>{if(!matching.some(v=>v.id===version))setVersion(matching[0]?.id||'')},[versions,versionGame,versionLoader,showBeta]);
 const choose=async(p:Json)=>{const seq=++selectionSequence.current;setVersionGame(minecraft);setVersionLoader(loader);setShowBeta(false);setProject(p);setLocal(null);setVersions([]);setVersion('');setName(p.title);setError('');setPending(true);setJobId('');try{const r:Json[]=await api('pack-versions',{project:p.project_id});if(selectionSequence.current===seq)setVersions(r)}catch(e){setError(String(e))}finally{setPending(false)}};
 const pick=async()=>{setError('');setPending(true);try{const path=await invoke<string|null>('pick_pack');if(!path)return;const r=await api('pack-preview',{path});setLocal({...r,path});setProject(null);setName(r.name);setOptional(true);setJobId('')}catch(e){setError(String(e))}finally{setPending(false)}};
 const upgrade=async(i:Json)=>{setPending(true);setError('');try{const r=await api('pack-install',{project:project!.project_id,version,name:i.instance.name+' · '+selected?.version_number,optional,upgradeFrom:i.instance.instanceId});setJobId(r.jobId);onRefresh()}catch(e){setError(String(e))}finally{setPending(false)}};
 const install=async()=>{setPending(true);setError('');try{const r=await api(local?'pack-import':'pack-install',local?{path:local.path,sha512:local.sha512,name,optional}:{project:project!.project_id,version,name,optional});setJobId(r.jobId);onRefresh()}catch(e){setError(String(e))}finally{setPending(false)}};
 const retry=async()=>{setPending(true);try{const r=await api('job-retry',{jobId});setJobId(r.jobId);onRefresh()}catch(e){setError(String(e))}finally{setPending(false)}};
 const selected=versions.find(v=>v.id===version);const installedPacks=installed.filter(i=>i.pack?.project&&i.pack.project===project?.project_id);
 const resetFilters=()=>{setCategory('');setMinecraft('');setLoader('');setQuery('');setSubmitted('');setSort('downloads')};
 return <div className="packs-page"><div className="pack-hero"><span className="scene-kicker">YOUR NEXT ADVENTURE</span><h1>{t("下一场冒险，装好就出发。")}</h1><p>{t("整套玩法，一次装好。也可以导入从社区下载的整合包。")}</p><button className="button" disabled={pending||locked} onClick={pick}><FolderOpen size={17}/>{t("导入整合包")}</button><small className="pack-import-help">{t("支持 .mrpack、HMCL / PCL 导出的完整 MCBBS ZIP")}</small></div>
 {error&&<div className="alert" role="alert">{<ServiceMessage text={error}/>}</div>}
 {(project||local)?<section className="panel pack-selection"><button className="back" disabled={locked} onClick={()=>{setProject(null);setLocal(null);setJobId('')}}><ArrowLeft size={16}/>{t("返回整合包")}</button><div className="pack-heading">{project?.icon_url?<img src={project.icon_url} alt=""/>:<Package size={48}/>}<div><h2>{local?.name||project?.title}</h2><p>{local?.summary||project?.description}</p></div></div>
 {installedPacks.map(i=><div className="notice" key={i.instance.instanceId}><span>{t("已安装：")}{i.instance.name} · {i.pack.version}</span><button className="button" onClick={()=>onOpen(i.instance.instanceId)}>{t("打开游戏")}</button><button className="button" disabled={locked||i.running||!version||i.pack.versionId===version||!selected?.game_versions?.includes(i.instance.minecraft)} onClick={()=>upgrade(i)}>{t("升级到所选版本")}</button></div>)}<p className="muted">{t("升级会创建新版并复制存档；旧版保留。新版使用作者配置，暂只迁移同一 Minecraft 版本的存档。")}</p><label>{t("在游戏库中的名字")}<input value={name} maxLength={80} disabled={locked||!!jobId} onChange={e=>setName(e.target.value)}/></label>
 {!local&&<><div className="pack-version-filters"><label>{t("游戏版本")}<Select value={versionGame} disabled={locked||!!jobId} onChange={e=>setVersionGame(e.target.value)}><option value="">{t("所有游戏版本")}</option>{[...new Set(versions.flatMap(v=>v.game_versions||[]))].map(v=><option key={v} value={v}>{v}</option>)}</Select></label><label>{t("加载器")}<Select value={versionLoader} disabled={locked||!!jobId} onChange={e=>setVersionLoader(e.target.value)}><option value="">{t("自动选择")}</option>{[...new Set(versions.flatMap(v=>v.loaders||[]))].map(v=><option key={v} value={v}>{v}</option>)}</Select></label></div><label className="pack-optional"><input type="checkbox" checked={showBeta} disabled={locked||!!jobId} onChange={e=>setShowBeta(e.target.checked)}/>{t("显示测试版与预览版")}</label></>}
 {!local&&<label>{t("整合包版本")}<Select value={version} disabled={locked||!!jobId||!matching.length} onChange={e=>setVersion(e.target.value)}>{matching.map(v=><option key={v.id} value={v.id}>{v.name} · {v.game_versions?.join(', ')}{v.version_type!=='release'?` · ${v.version_type==='beta'?t("测试版"):t("预览版")}`:''}</option>)}</Select></label>}
 <p className="pack-environment">{local?t("Minecraft {0} · {1} · {2} 个文件",local.minecraft,local.loader.kind,local.files):(selected?`Minecraft ${selected.game_versions?.join(', ')} · ${selected.loaders?.join(' / ')}`:pending?t("正在加载版本…"):t("没有符合筛选条件的正式版，可以切换游戏版本或显示测试版"))}</p>
 {(!local||local.optional>0)&&<label className="pack-optional"><input type="checkbox" checked={optional} disabled={locked||!!jobId} onChange={e=>setOptional(e.target.checked)}/>{t("同时安装作者标记的可选内容")}{local?.optional?t("（{0} 项）",local.optional):''}</label>}<p className="muted">{t("每个整合包拥有自己的配置与存档。已有游戏不会被覆盖。")}</p>
 {currentJob&&<JobProgress job={currentJob} onRefresh={onRefresh} hideRetry/>}
 <div className="actions">{currentJob?.status==='done'?<button className="button primary" onClick={()=>onOpen(currentJob.result.id)}>{t("进入我的游戏")}</button>:['error','cancelled'].includes(currentJob?.status)&&currentJob?.retryable?<button className="button primary" disabled={locked} onClick={retry}>{t("继续安装")}</button>:<button className="button primary" disabled={locked||!name.trim()||(!local&&!version)} onClick={install}>{locked?<LoaderCircle className="spin" size={18}/>:<Download size={18}/>} {locked?(currentJob?t("正在准备整合包…"):t("正在加载…")):t("安装整合包")}</button>}</div></section>:<><form className="pack-search" onSubmit={e=>{e.preventDefault();if(submitted===query.trim())void search();else setSubmitted(query.trim())}}><Search size={19}/><input aria-label={t("搜索整合包")} placeholder={t("搜索整合包，发现新的玩法…")} value={query} onChange={e=>setQuery(e.target.value)}/><button className="button primary" disabled={loading}>{t("搜索")}</button></form><div className="pack-categories" role="group" aria-label={t("整合包分类")}>{['',...categories].map(c=><button key={c} className={category===c?'active':''} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c?t(categoryLabels[c]||c):t("全部玩法")}</button>)}</div><div className="pack-filters"><label>{t("游戏版本")}<Select aria-label={t("筛选游戏版本")} value={minecraft} onChange={e=>setMinecraft(e.target.value)}><option value="">{t("不限版本")}</option>{gameVersions.map(v=><option key={v.id} value={v.id}>{v.id}</option>)}</Select></label><label>{t("加载器")}<Select aria-label={t("筛选加载器")} value={loader} onChange={e=>setLoader(e.target.value)}><option value="">{t("不限加载器")}</option><option value="fabric">Fabric</option><option value="forge">Forge</option><option value="neoforge">NeoForge</option><option value="quilt">Quilt</option></Select></label><label>{t("排序")}<Select aria-label={t("整合包排序")} value={sort} onChange={e=>setSort(e.target.value)}><option value="downloads">{t("下载最多")}</option><option value="relevance">{t("最相关")}</option><option value="updated">{t("最近更新")}</option><option value="newest">{t("最新发布")}</option><option value="follows">{t("收藏最多")}</option></Select></label><button className="text-link" onClick={resetFilters}>{t("重置筛选")}</button></div><div className="section-heading"><h2>{submitted||category||minecraft||loader?t("探索结果"):t("大家都在玩")}</h2><span className="muted">{loading?t("查找中…"):t("{0} 个结果",total.toLocaleString(getLocale()))} · Modrinth</span></div>
 {loading?<div className="empty"><LoaderCircle className="spin"/><p>{t("寻找下一场冒险…")}</p></div>:error?<div className="empty"><h3>{t("暂时无法加载整合包")}</h3><p>{t("筛选条件已保留，检查网络后重试。")}</p><button className="button" onClick={()=>search()}>{t("重新加载")}</button></div>:!hits.length?<div className="empty"><Package size={36}/><p>{t("没有找到整合包，试试减少筛选条件或使用英文名称。")}</p><button className="button" onClick={resetFilters}>{t("清除搜索与筛选")}</button></div>:<div className="pack-grid">{hits.map(p=><button className="pack-card" key={p.project_id} onClick={()=>choose(p)}>{p.icon_url?<img src={p.icon_url} loading="lazy" alt=""/>:<Package size={50}/>}<div><h3>{p.title}</h3><small>by {p.author}</small><p>{p.description}</p><div className="pack-tags">{(p.display_categories||p.categories||[]).filter((c:string)=>categoryLabels[c]).slice(0,3).map((c:string)=><span key={c}>{t(categoryLabels[c])}</span>)}</div><span>{(p.downloads||0).toLocaleString(getLocale())} {t(" 次下载")}</span><small className="pack-updated">{new Date(p.date_modified).toLocaleDateString(getLocale())} {t(" 更新")}{installed.some(i=>i.pack?.project===p.project_id)?t(" · 已安装"):''}</small></div><span className="pack-card-cta">{t("选择版本 →")}</span></button>)}</div>}
 <div className="pack-pagination"><button className="button" disabled={loading||offset===0} onClick={()=>search(Math.max(0,offset-24))}>{t("上一页")}</button><span>{t("第 ")}{Math.floor(offset/24)+1} {t(" 页")}</span><button className="button" disabled={loading||offset+24>=total||offset>=9984} onClick={()=>search(offset+24)}>{t("下一页")}</button></div></>}
 </div>
}
