import {t,getLocale,ServiceMessage} from './i18n';
import React, {Children, isValidElement, useEffect, useId, useRef, useState} from 'react';
import {createPortal} from 'react-dom';
import {Check, ChevronDown} from 'lucide-react';

// A desktop-style selector. Keep the existing controlled form contract.
export function Select({children,value,onChange,disabled,...props}:React.SelectHTMLAttributes<HTMLSelectElement>){
 const options=Children.toArray(children).filter(isValidElement).map(child=>{const p=child.props as React.OptionHTMLAttributes<HTMLOptionElement>;return {value:String(p.value??p.children),label:p.children,disabled:!!p.disabled}});
 const selected=Math.max(0,options.findIndex(o=>o.value===String(value??'')));
 const [open,setOpen]=useState(false),[active,setActive]=useState(selected),[position,setPosition]=useState({left:0,top:0,width:0,maxHeight:280});
 const trigger=useRef<HTMLButtonElement>(null),popup=useRef<HTMLDivElement>(null),id=useId();
 const close=()=>setOpen(false);
 const choose=(index:number)=>{const option=options[index];if(!option||option.disabled)return;onChange?.({target:{value:option.value},currentTarget:{value:option.value}} as React.ChangeEvent<HTMLSelectElement>);close();trigger.current?.focus()};
 useEffect(()=>{if(!open)return;const anchor=trigger.current!;const rect=anchor.getBoundingClientRect();const below=window.innerHeight-rect.bottom-12;const above=rect.top-12;const height=Math.min(280,Math.max(below,above));setPosition({left:Math.max(8,Math.min(rect.left,window.innerWidth-rect.width-8)),top:below>=Math.min(280,above)?rect.bottom+5:Math.max(8,rect.top-height-5),width:rect.width,maxHeight:height});setActive(selected);const outside=(e:PointerEvent)=>{if(!anchor.contains(e.target as Node)&&!popup.current?.contains(e.target as Node))close()};const scroll=(e:Event)=>{if(!popup.current?.contains(e.target as Node))close()};document.addEventListener('pointerdown',outside);document.addEventListener('scroll',scroll,true);window.addEventListener('resize',close);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('scroll',scroll,true);window.removeEventListener('resize',close)}},[open]);
 useEffect(()=>{if(open)popup.current?.querySelector(`[data-index="${active}"]`)?.scrollIntoView({block:'nearest'})},[active,open]);
 useEffect(()=>{if(disabled)close()},[disabled]);
 const move=(direction:number)=>{let next=active;for(let step=0;step<options.length;step++){next=(next+direction+options.length)%options.length;if(!options[next].disabled){setActive(next);return}}};
 return <><button ref={trigger} id={props.id} type="button" className="desktop-select" disabled={disabled} aria-label={props['aria-label']} role="combobox" aria-haspopup="listbox" aria-expanded={open} aria-controls={open?id:undefined} aria-activedescendant={open?`${id}-${active}`:undefined} onClick={()=>setOpen(!open)} onKeyDown={e=>{if(['ArrowDown','ArrowUp','Home','End','Enter',' ','Escape','Tab'].includes(e.key)){if(e.key!=='Tab')e.preventDefault();if(e.key==='Escape'||e.key==='Tab'){if(open&&e.key==='Escape')e.stopPropagation();close();return}if(!open){setOpen(true);return}if(e.key==='ArrowDown')move(1);if(e.key==='ArrowUp')move(-1);if(e.key==='Home')setActive(0);if(e.key==='End')setActive(options.length-1);if(e.key==='Enter'||e.key===' ')choose(active)}else if(e.key.length===1){const index=options.findIndex(o=>!o.disabled&&String(o.label).toLowerCase().startsWith(e.key.toLowerCase()));if(index>=0){if(!open)setOpen(true);setActive(index)}}}}><span>{options[selected]?.label||t("请选择")}</span><ChevronDown size={15}/></button>{open&&createPortal(<div ref={popup} id={id} role="listbox" aria-label={props['aria-label']||t("可用选项")} className="desktop-select-menu" style={position}>{options.map((option,index)=><div key={`${option.value}-${index}`} id={`${id}-${index}`} role="option" aria-selected={index===selected} aria-disabled={option.disabled} data-index={index} className={`desktop-select-option ${index===active?'highlighted':''} ${option.disabled?'disabled':''}`} onMouseDown={e=>e.preventDefault()} onMouseMove={()=>setActive(index)} onClick={()=>choose(index)}><span>{option.label}</span>{index===selected&&<Check size={14}/>}</div>)}</div>,document.body)}</>;
}
